# Generated by Django 4.0.3 on 2022-03-13 18:17

from django.db import migrations, models
import macaddress.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouterDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loop_back', models.GenericIPAddressField()),
                ('sap_id', models.CharField(default='', max_length=18, unique=True)),
                ('host_name', models.CharField(default='', max_length=14, unique=True)),
                ('mac_address', macaddress.fields.MACAddressField(blank=True, default='', integer=True, max_length=17, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['loop_back'],
            },
        ),
    ]
