# Generated by Django 4.0.3 on 2022-03-13 18:52

from django.db import migrations, models
import macaddress.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routerdetails',
            name='loop_back',
            field=models.GenericIPAddressField(unique=True),
        ),
        migrations.AlterField(
            model_name='routerdetails',
            name='mac_address',
            field=macaddress.fields.MACAddressField(blank=True, default='', integer=True, max_length=17, null=True, unique=True),
        ),
    ]
